[package]
name = "rust_asm"
version = "0.1.0"
edition = "2021"

[dependencies]
amiquip = "0.4.2"
rand = "0.8.5"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
tokio = { version = "1.42.0", features = ["full"] }
